### PR TITLE
Address review remarks from #129

### PR DESCRIPTION
**Pull request by pfrenssen**
Ref. https://github.com/Behat/Gherkin/pull/129#discussion_r385131437

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
These are both valid review comments from @stof, I regret merging so fast since the last commits

Is making this private a BC break now? I guess the project doesn't have a stated BC policy

**Comment by guilliamxavier** [comment]
@ciaranmcnulty: What about just releasing a v4.6.2 ASAP?

**Comment by pfrenssen** [comment]
I don't think protected methods are usually considered to be part of a project's API, only the public methods are.

**Comment by guilliamxavier** [comment]
👍 Moreover this method was only introduced in the patch-version 4.6.1, so I think there is no reason to hold this off

**Comment by stof** [comment]
@pfrenssen protected methods are covered by backward compatibility, as changing them breaks child classes (and if you don't care about child classes, why using protected rather than private ?)

**Comment by pfrenssen** [comment]
@stof OK I just opened this because it was your suggestion to change this to private. I don't care about this. Closing.

**Pull request closed without merging**
