### PR TITLE
Test with PHP 7.3

### PR DESCRIPTION
**Pull request by phil-davis**
PR #143 repeated PHP 7.2

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Oops!

**Comment by phil-davis** [comment]
Let's see if CI is happy running the tests on PHP 7.3!

**Comment by ciaranmcnulty** [comment]
Worked locally for me on 7.3, just typo'd the travis yaml

**Comment by phil-davis** [comment]
This does not effect the content of the v4.6.0 release. So there is not really any need to make v4.6.1.
Just merge this so that future CI does run PHP 7.3

**Comment by ciaranmcnulty** [comment]
Thanks for the quick fix @phil-davis

**Comment by phil-davis** [comment]
NP - I just happened to type ``composer update`` 10 minutes after you had made the new release, so came to look at it.

**Pull request merged**
