### PR TITLE
Closes #197 - Provided outline title when creating example node

### LINKED ISSUE #197: When creating ExampleNode outline title is never passed to contructor
broken in #161 
https://github.com/Behat/Gherkin/commit/dfc47a2f796c99b8b6e6195ec277adc4ea1e36e2#diff-6e02ff2c049819aa5946c6a1577b66c4ebece9a0c2275c5aa5f7c5d209e9eba2R227

title is never passed

### PR DESCRIPTION
**Pull request by latvianization**

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
It worries me we don't have _any_ tests that fail as a result of this

**Comment by latvianization** [comment]
Community is our testers :)

**Comment by latvianization** [comment]
I don't want to rush anyone, but by what principles PR is merged and when this could be released as tag? Or should i just rollback and wait?

**Comment by ciaranmcnulty** [comment]
I'd use an older version as that'll unblock you immediately

**Comment by ciaranmcnulty** [comment]
OK I added a unit test for this case

**Comment by ciaranmcnulty** [comment]
I managed to do a release of `4.7.2` with this in

**Comment by latvianization** [comment]
> I managed to do a release of `4.7.2` with this in

Thanks 👍👍

**Pull request merged**
